s = input('Digite um texto:' )
s = s.replace('a', '4')
s = s.replace('t', '7')
s = s.replace('e', '3')
s = s.replace('s', '5')
s = s.replace('B', '8')
s = s.replace('l', '1')
s = s.replace('o', '0')
print (s)